#!/bin/bash

set -e
set -x
set -o pipefail

CORPUSDIR=toradocu
for dirname in $CORPUSDIR/*; do
  [ -d "$dirname" ] || continue

  basename=`basename $dirname`
  if [ "$basename" = "commons-rng" ] ; then
    echo "not running randoop on $basename"
    continue
  fi

  log="../logs/$basename-randoop-log.txt"

  if [[ -e "$dirname/build.gradle" ]]; then
    echo "running randoop on $basename"
    (cd $dirname; ./gradlew prepareForCoverage 2>&1 | tee $log)
  fi
done
